### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by toddleish** [mlsmithjr/transcoder#14]
On my first conversion attempt using the stock config file, I get this error:
```[centos@psd-nxtranscode-01 transcode]$ sudo pytranscoder --dry-run AdobeStock_27472987.mov
[sudo] password for centos:
[centos@psd-nxtranscode-01 transcode]$ pytranscoder --dry-run AdobeStock_27472987.mov
Traceback (most recent call last):
  File "/home/centos/.local/bin/pytranscoder", line 11, in <module>
    sys.exit(main())
  File "/home/centos/.local/lib/python3.6/site-packages/pytranscoder/transcode.py", line 340, in main
    start()
  File "/home/centos/.local/lib/python3.6/site-packages/pytranscoder/transcode.py", line 416, in start
    configfile = ConfigFile(DEFAULT_CONFIG)
  File "/home/centos/.local/lib/python3.6/site-packages/pytranscoder/config.py", line 32, in __init__
    yml = yaml.load(f, Loader=yaml.Loader)
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib64/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/local/lib64/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib64/python3.6/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "/home/centos/.transcode.yml", line 42, column 9
expected <block end>, but found '<scalar>'
  in "/home/centos/.transcode.yml", line 49, column 19
```

Any ideas on what could be wrong?

**Comment by mlsmithjr** [comment]
Line 48 of your transcode.yml has a pair of mismatched quotes.  Just edit that line and use either double or single quotes there.
The sample.yml and transcode.yml files in the standard build have been corrected.  Thanks.
