### ISSUE TITLE
KeyError generated when running Quick Start .transcode.yml

### ISSUE THREAD

**Issue by randomparity** [mlsmithjr/transcoder#21]
Using the quick start settings from [ReadTheDocs](https://pytranscoder.readthedocs.io/en/latest/configuration/quickstart.html), executing a dry run on an MP4 or MKV file generates the following error:

`pytranscoder -v --dry-run video.mp4 
Traceback (most recent call last):
  File "/home/sysadmin/.local/bin/pytranscoder", line 8, in <module>
    sys.exit(main())
  File "/home/sysadmin/.local/lib/python3.8/site-packages/pytranscoder/transcode.py", line 341, in main
    start()
  File "/home/sysadmin/.local/lib/python3.8/site-packages/pytranscoder/transcode.py", line 463, in start
    host.enqueue_files(files)
  File "/home/sysadmin/.local/lib/python3.8/site-packages/pytranscoder/transcode.py", line 274, in enqueue_files
    print(str(media_info))
  File "/home/sysadmin/.local/lib/python3.8/site-packages/pytranscoder/media.py", line 42, in __str__
    subs = [s['stream'] + ':' + s['lang'] + ':' + s['default'] for s in self.subtitle]
  File "/home/sysadmin/.local/lib/python3.8/site-packages/pytranscoder/media.py", line 42, in <listcomp>
    subs = [s['stream'] + ':' + s['lang'] + ':' + s['default'] for s in self.subtitle]
KeyError: 'default'
`
pytranscoder-ffmpeg version:

`python3 -m pip show pytranscoder-ffmpeg
Name: pytranscoder-ffmpeg
Version: 2.2.2
Summary: A ffmpeg workflow manager for transcoding
Home-page: https://github.com/mlsmithjr/transcoder
Author: Marshall L Smith Jr
Author-email: marshallsmithjr@gmail.com
License: UNKNOWN
Location: /home/sysadmin/.local/lib/python3.8/site-packages
Requires: pyyaml, crayons
Required-by: 
`
Operating system is Ubuntu 20.04.2 LTS:

`cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
`
Running ffprobe generates the following output for video.mp4:

`ffprobe video.mp4 
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.20.100
  Duration: 00:34:04.85, start: 0.000000, bitrate: 919 kb/s
    Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 591 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 23.98 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Side data:
      audio service type: main
    Stream #0:2(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 126 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:3(eng): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s (default)
    Metadata:
      handler_name    : SubtitleHandler
    Stream #0:4(swe): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s
    Metadata:
      handler_name    : SubtitleHandler
    Stream #0:5(nor): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s
    Metadata:
      handler_name    : SubtitleHandler
    Stream #0:6(ger): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s
    Metadata:
      handler_name    : SubtitleHandler
    Stream #0:7(fin): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s
    Metadata:
      handler_name    : SubtitleHandler
`

**Comment by lovesegfault** [comment]
I'm getting this too
