### ISSUE TITLE
I am getting Traceback (most recent call last) issue

### ISSUE THREAD

**Issue by javeedrahman** [mlsmithjr/transcoder#9]
Hi,
I have followed the installaion guide and installed all the required dependecies.
While running the command --> **pytranscoder --dry-run sample.mkv**

I am just testing with 35mb file without changing any config in trancode.yml.

I am getting following error
```
Traceback (most recent call last):
  File "/home/procserverjh/tmp/pytranscoder/bin/pytranscoder", line 8, in <module>
    sys.exit(main())
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/pytranscoder/transcode.py", line 341, in main
    start()
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/pytranscoder/transcode.py", line 417, in start
    configfile = ConfigFile(DEFAULT_CONFIG)
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/pytranscoder/config.py", line 32, in __init__
    yml = yaml.load(f, Loader=yaml.Loader)
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/procserverjh/tmp/pytranscoder/lib/python3.7/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "/home/procserverjh/.transcode.yml", line 42, column 9
expected <block end>, but found '<scalar>'
  in "/home/procserverjh/.transcode.yml", line 49, column 19

```

**Comment by mlsmithjr** [comment]
Could you include the transcode.yml you are using? I know you said it was
the unmodified sample included with the code but the line and column
indicated in the error doesn't correspond to what I have in the current
sample.
Thanks.

**Comment by javeedrahman** [comment]
Hi,
Thank you for the reply. I have included the transcode.yml which i have copied from simple.yml.
I am using Python 3.7, installed PlexAPI. Should i need to install any other dependencies.
I have also tried in virutalenv but same error. 
Here is the command
**pytranscoder -y transcode.yml --dry-run sample.mkv**
Thanks.

Here is the pytranscoder code:
```
#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from pytranscoder.transcode import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by mlsmithjr** [comment]
Did you attach the yml file?  It's not part of the email, or maybe github
stripped it out.
Alternately you can use pastebin.com and send me the link.

**Comment by JasonPyMe** [comment]
Hello, I am not sure if the other person having this issue uploaded the YAML file but, I am having the same issue.  I am running the following, should be the latest versions.

Python 3.8.2
Pytranscoder 2.0.14
Ubuntu Desktop 20.04
Nvidia RTX 4000 GPU - 440 drivers
[transcode.yml.txt](https://github.com/mlsmithjr/transcoder/files/5226705/transcode.yml.txt)

I have uploaded my YAML file which is pretty much the same as the simple.yml with just a change to the default directory and a ffmpeg setting change.

**Comment by mlsmithjr** [comment]
Oops, there is a pair of mismatched quotes on line 48.  Just swap the single quote for a double or vise-versa.

**Comment by JasonPyMe** [comment]
That worked thank you for the quick response.
